# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 676d6da2cc75384e0e42c574c5b334f9be4a147d859985a3d9407220797598f84026c0ad9920cde7ee897bf4108ee2a115270887db6b599e72b125dd596825c6

test:
  secret_key_base: fede62fda0af50c5a8b2b42073bef9bda5385d1ffe0f7d789ac10f73ac55994c1579058efc936f1b55cd9f9b5c92e008f93211a4523732a1fa0e944ed1614078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
